export const innerspagesListData = {
	emptyMessage: "No inner pages available at the moment.",
	defaultAltText: "Inner page",
	carouselAriaLabel: "Our inner pages",
	subtitle: "Inners pages",
	title: "take a look at the inner pages",
	divider: true,
	align: "center" as const,
	items: [
		{
			id: 1,
			image: "/sections/page-about.jpg",
			altText: "About",
			link: "/about",
			caption: "About",
		},
		{
			id: 2,
			image: "/sections/page-history.jpg",
			altText: "History",
			link: "/history",
			caption: "History",
		},
		{
			id: 3,
			image: "/sections/page-menu.jpg",
			altText: "Menu",
			link: "/menu",
			caption: "Menu",
		},
		{
			id: 4,
			image: "/sections/page-menu-sidebar.jpg",
			altText: "Menu Sidebar",
			link: "/menu-sidebar",
			caption: "Menu Sidebar",
		},
		{
			id: 5,
			image: "/sections/page-menu-tabs.jpg",
			altText: "Menu Tabs",
			link: "/menu-tabs",
			caption: "Menu Tabs",
		},
		{
			id: 5,
			image: "/sections/page-menu-full-width.jpg",
			altText: "Menu Full Width",
			link: "/menu-full-width",
			caption: "Menu Full Width",
		},
		{
			id: 6,
			image: "/sections/page-services.jpg",
			altText: "Services",
			link: "/services",
			caption: "Services",
		},
		{
			id: 7,
			image: "/sections/page-team.jpg",
			altText: "Team",
			link: "/team",
			caption: "Team",
		},
		{
			id: 8,
			image: "/sections/page-comming-soon.jpg",
			altText: "Coming Soon",
			link: "/coming-soon",
			caption: "Coming Soon",
		},
		{
			id: 9,
			image: "/sections/page-404.jpg",
			altText: "404",
			link: "/404",
			caption: "404",
		},
	],
};
