export const sliderHeroData = {
	emptyMessage: "No hero slides available at the moment.",
	mainCarouselAriaLabel: "Main content carousel",
	prevButtonAriaLabel: "Previous slide",
	nextButtonAriaLabel: "Next slide",
	paginationBulletAriaLabel: "Go to slide {index}",
	firstSlideMessage: "This is the first slide",
	lastSlideMessage: "This is the last slide",
	items: [
		{
			id: 1,
			image: "/hero/hero-1.jpg",
			altText: "hero-1",
			subtitle: "Welcome to Our Restaurant",
			title: "the best food for the best moments",
			desc: "Step into a space where nature-inspired cuisine comes alive. Each dish is a masterpiece that celebrates organic flavors and visual harmony.",
			link: "/menu",
			textLink: "See Our Menu",
		},
		{
			id: 2,
			image: "/hero/hero-2.jpg",
			altText: "hero-2",
			subtitle: "The most delicious",
			title: "check out our gourmet menu",
			desc: "The restaurant is an organic space reflective of nature inspired cuisine. The interplay of textures and colour brings life and a vibrance that embraces the restaurant's place in the dress circle.",
			link: "/menu",
			textLink: "See Our Menu",
		},
		{
			id: 3,
			image: "/hero/hero-3.jpg",
			altText: "hero-3",
			subtitle: "Flavors that Spark Emotion",
			title: "An Exceptional Journey of Taste",
			desc: "Our cuisine blends technique, creativity, and passion to deliver unforgettable dishes on every visit.",
			link: "/menu",
			textLink: "See Our Menu",
		},
		{
			id: 4,
			image: "/hero/hero-4.jpg",
			altText: "hero-4",
			subtitle: "Specialists in Premium Meats",
			title: "The Best Cuts, The Best Flavor",
			desc: "Surrender to the juiciness and aroma of our selected meats, cooked to perfection in a cozy atmosphere.",
			link: "/menu",
			textLink: "See Our Menu",
		},
		{
			id: 5,
			image: "/hero/hero-5.jpg",
			altText: "hero-5",
			subtitle: "Fusion of Textures and Flavors",
			title: "Your New Culinary Paradise",
			desc: "Every detail is designed to offer you a unique culinary experience, where flavor, ambiance, and service blend in perfect harmony.",
			link: "/menu",
			textLink: "See Our Menu",
		},
	],
};

export const sliderHeroIntroData = {
	emptyMessage: "No hero slides available at the moment.",
	mainCarouselAriaLabel: "Main content carousel",
	prevButtonAriaLabel: "Previous slide",
	nextButtonAriaLabel: "Next slide",
	paginationBulletAriaLabel: "Go to slide {index}",
	firstSlideMessage: "This is the first slide",
	lastSlideMessage: "This is the last slide",
	items: [
		{
			id: 1,
			image: "/hero/hero-1.jpeg",
			altText: "hero-1",
			subtitle: "Welcome to Our Restaurant",
			title: "LaCasa - Restaurant",
			desc: "Experience authentic flavors and warm hospitality at LaCasa Restaurant & Cafe. Located in Negombo, Sri Lanka, we offer a delightful dining experience with the finest ingredients and exceptional service.",
			link: "/",
			textLink: "Visit Us",
		},
	],
};
