export const galleryData = {
	subtitle: "Our Gallery",
	title: "Explore The New Tastee",
	phrase:
		"The first restaurant proprietor is believed to have been one A. Boulanger, a soup vendor, who opened his business in 1765.",
	divider: true,
	align: "center",
	emptyMessage: "No gallery items available at the moment.",
	errorMessage: "Error loading gallery:",
	lightboxOpenLabel: "Open lightbox",
	lightboxPrevAriaLabel: "Previous image",
	lightboxNextAriaLabel: "Next image",
	lightboxCloseAriaLabel: "Close lightbox",
	items: [
		{
			id: 1,
			image: "/gallery/gallery-1a.jpg",
			title: "Spring Roll",
			altText: "Spring Roll",
			subtitle: "Food",
		},
		{
			id: 2,
			image: "/gallery/gallery-2a.jpg",
			title: "Dinner Series",
			altText: "Dinner Series",
			subtitle: "Food",
		},
		{
			id: 3,
			image: "/gallery/gallery-3a.jpg",
			title: "Bevereges",
			altText: "Bevereges",
			subtitle: "Drinks",
		},
		{
			id: 4,
			image: "/gallery/gallery-4a.jpg",
			title: "Great Moments",
			altText: "Great Moments",
			subtitle: "Events",
		},
		{
			id: 5,
			image: "/gallery/gallery-5a.jpg",
			title: "Beautiful Spaces",
			altText: "Beautiful Spaces",
			subtitle: "Locations",
		},
		{
			id: 6,
			image: "/gallery/gallery-6a.jpg",
			title: "Pleasant Spaces",
			altText: "Pleasant Spaces",
			subtitle: "Locations",
		},
		{
			id: 7,
			image: "/gallery/gallery-7a.jpg",
			title: "House Recipe",
			altText: "House Recipe",
			subtitle: "Food",
		},
		{
			id: 8,
			image: "/gallery/gallery-8a.jpg",
			title: "Food and Wine",
			altText: "Food and Wine",
			subtitle: "Food",
		},
		{
			id: 9,
			image: "/gallery/gallery-9a.jpg",
			title: "Pleasant Spaces",
			altText: "Pleasant Spaces",
			subtitle: "Locations",
		},
		{
			id: 10,
			image: "/gallery/gallery-10a.jpg",
			title: "House Recipe",
			altText: "House Recipe",
			subtitle: "Food",
		},
		{
			id: 11,
			image: "/gallery/gallery-11a.jpg",
			title: "Food and Wine",
			altText: "Food and Wine",
			subtitle: "Food",
		},
		{
			id: 12,
			image: "/gallery/gallery-12a.jpg",
			title: "House Recipe",
			altText: "House Recipe",
			subtitle: "Food",
		},
	],
};
